[en]
work = "Work Experience"
present = "Present"
education = "Education"
education_in = "in"
courses = "Courses"
leadership = "Leadership & Activities"
projects = "Projects"
skills = "Skills, Languages, Interests"
languages = "Languages"
interests = "Interests"
awards = "Honors and Awards"
issued = "Issued by"
honors = "Honors"
certificates = "Licenses and Certifications"
publications = "Research and Publications"
published = "Published on"
press = "In press"
references = "References"
updated = "This document was last updated on"
updated_using = "using"
january = "January"
february = "February"
march = "March"
april = "April"
may = "May"
june = "June"
july = "July"
august = "August"
september = "September"
october = "October"
november = "November"
december = "December"

[fr]
work = "Expérience Professionnelle"
present = "Présent"
education = "Éducation"
education_in = "in"
courses = "Cours"
leadership = "Funktionen & Aktivitäten"
projects = "Projets"
skills = "Fähigkeiten, Sprachen, Interessen"
languages = "Langues"
interests = "Intérêts"
awards = "Titel und Auszeichnungen"
issued = "Émis par"
honors = "Honneurs"
certificates = "Licences et Certifications"
publications = "Forschung und Veröffentlichungen"
published = "Veröffentlicht am"
press = "In der Presse"
references = "Referenzen"
updated = "Ce document a été mis à jour le"
updated_using = "mit"
january = "Janvier"
february = "Février"
march = "Mars"
april = "Avril"
may = "Mai"
june = "Juin"
july = "Juillet"
august = "Août"
september = "Septembre"
october = "Octobre"
november = "Novembre"
december = "Décembre"
