[en]
summary = "Summary"
work = "Work Experience"
present = "Present"
education = "Education"
education_in = "in"
courses = "Courses"
leadership = "Leadership & Activities"
projects = "Projects"
skills = "Skills"
languages = "Languages"
interests = "Interests"
and = "and"
awards = "Honors and Awards"
issued = "Issued by"
honors = "Honors"
certificates = "Licenses and Certifications"
publications = "Research and Publications"
published = "Published on"
press = "In press"
references = "References"
updated = "This document was last updated on"
updated_using = "using"
january = "January"
february = "February"
march = "March"
april = "April"
may = "May"
june = "June"
july = "July"
august = "August"
september = "September"
october = "October"
november = "November"
december = "December"
objective = "Objective"

[en.abbreviate]
january = 3
february = 3
march = 3
april = 3
may = 3
june = 3
july = 3
august = 3
september = 3
october = 3
november = 3
december = 3

[fr]
summary = "Résumé"
work = "Expérience Professionnelle"
present = "Présent"
education = "Éducation"
education_in = "en"
courses = "Cours"
leadership = "Funktionen & Aktivitäten"
projects = "Projets"
skills = "Compétences"
languages = "Langues"
interests = "Intérêts"
and = "et"
awards = "Titel und Auszeichnungen"
issued = "Émis par"
honors = "Honneurs"
certificates = "Licences et Certifications"
publications = "Forschung und Veröffentlichungen"
published = "Veröffentlicht am"
press = "In der Presse"
references = "Referenzen"
updated = "Ce document a été mis à jour le"
updated_using = "mit"
january = "Janvier"
february = "Février"
march = "Mars"
april = "Avril"
may = "Mai"
june = "Juin"
july = "Juillet"
august = "Août"
september = "Septembre"
october = "Octobre"
november = "Novembre"
december = "Décembre"
objective = "Objectif"

[fr.abbreviate]
january = 4
february = 4
march = 4
april = 3
may = 3
june = 4
july = 5
august = 4
september = 4
october = 3
november = 3
december = 3
