[en]
work = "Work Experience"
present = "Present"
education = "Education"
education_in = "in"
courses = "Courses"
leadership = "Leadership & Activities"
projects = "Projects"
skills = "Skills, Languages, Interests"
languages = "Languages"
interests = "Interests"
awards = "Honors and Awards"
issued = "Issued by"
honors = "Honors"
certificates = "Licenses and Certifications"
publications = "Research and Publications"
published = "Published on"
press = "In press"
references = "References"
updated = "This document was last updated on"
updated_using = "using"
january = "January"
february = "February"
march = "March"
april = "April"
may = "May"
june = "June"
july = "July"
august = "August"
september = "September"
october = "October"
november = "November"
december = "December"

[de]
work = "Arbeitserfahrungen"
present = "Jetzt"
education = "Bildung"
education_in = "in"
courses = "Kurse"
leadership = "Funktionen & Aktivitäten"
projects = "Projekte"
skills = "Fähigkeiten, Sprachen, Interessen"
languages = "Sprachen"
interests = "Interessen"
awards = "Titel und Auszeichnungen"
issued = "Ausgestellt von"
honors = "Titel"
certificates = "Lizenzen und Zertifizierungen"
publications = "Forschung und Veröffentlichungen"
published = "Veröffentlicht am"
press = "In der Presse"
references = "Referenzen"
updated = "Dieses Dokument wurde zuletzt aktualisiert am"
updated_using = "mit"
january = "Januar"
february = "Februar"
march = "März"
april = "April"
may = "Mai"
june = "Juni"
july = "Juli"
august = "August"
september = "September"
october = "Oktober"
november = "November"
december = "Dezember"

[pt-BR]
work = "Experiência de Trabalho"
present = "Presente"
education = "Educação"
education_in = "em"
courses = "Cursos"
leadership = "Liderança & Atividades"
projects = "Projetos"
skills = "Habilidades, Idiomas, Interesses"
languages = "Idiomas"
interests = "Interesses"
awards = "Honras e Prêmios"
issued = "Emitido por"
honors = "Honras"
certificates = "Licenças e Certificações"
publications = "Pesquisas e Publicações"
published = "Publicado em"
press = "Na imprensa"
references = "Referências"
updated = "Este documento foi atualizado pela última vez em"
updated_using = "usando"
january = "Janeiro"
february = "Fevereiro"
march = "Março"
april = "Abril"
may = "Maio"
june = "Junho"
july = "Julho"
august = "Agosto"
september = "Setembro"
october = "Outubro"
november = "Novembro"
december = "Dezembro"
